; =====================================================
; AIRA ESP32-S3 — PlatformIO Configuration
; =====================================================
[env:esp32-s3-devkitc-1]
platform  = espressif32
board     = esp32-s3-devkitc-1
framework = arduino

; Serial monitor
monitor_speed = 115200

; Libraries
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.5
    miguelbalboa/MFRC522  @ ^1.4.11

; Build flags
build_flags =
    -DCORE_DEBUG_LEVEL=0
